import type { Ambition, Bond, Person, PlaceId, Self, Skill } from "./types.js";
import { SKILLS, bandFor } from "./types.js";

export const HOUSEHOLDS = [
  { id: "vale", name: "Vale", color: "#c46a45" },
  { id: "market", name: "Market", color: "#2f6a4a" },
  { id: "porch", name: "Porch", color: "#355f78" },
  { id: "grove", name: "Grove", color: "#6f8f4e" },
] as const;

export function householdColor(id: string): string {
  return HOUSEHOLDS.find((house) => house.id === id)?.color ?? "#355f78";
}

export function householdName(id: string): string {
  return HOUSEHOLDS.find((house) => house.id === id)?.name ?? id;
}

function skills(partial: Partial<Record<Skill, number>>): Record<Skill, number> {
  const full = {} as Record<Skill, number>;
  for (const skill of SKILLS) full[skill] = partial[skill] ?? 8;
  return full;
}

interface Seed {
  id: string;
  name: string;
  age: number;
  gender: Person["gender"];
  household: string;
  home: PlaceId;
  spouse: string | null;
  guardians: string[];
  dependents: string[];
  self: Omit<Self, "ambition">;
  skills: Partial<Record<Skill, number>>;
  mood: string;
}

const SEEDS: Seed[] = [
  {
    id: "jevaary",
    name: "Jevaary",
    age: 38,
    gender: "male",
    household: "vale",
    home: "vale",
    spouse: "jevine",
    guardians: [],
    dependents: ["jevlin", "jevora"],
    mood: "steady, already counting the day",
    self: {
      temper: "steady and spare with words",
      want: "the field full before dusk",
      fear: "a child still out after dark",
      habit: "counts the food before he speaks",
      pull: ["farm", "haul", "watch"],
      custom: "provision",
    },
    skills: { farm: 72, haul: 68, cook: 22, forage: 28, teach: 18 },
  },
  {
    id: "jevine",
    name: "Jevine",
    age: 36,
    gender: "female",
    household: "vale",
    home: "vale",
    spouse: "jevaary",
    guardians: [],
    dependents: ["jevlin", "jevora"],
    mood: "warm, checking who has not eaten",
    self: {
      temper: "warm and organizing",
      want: "the hearth busy and the children heard",
      fear: "a quiet toddler",
      habit: "says a person's name when she speaks",
      pull: ["cook", "care", "mend"],
      custom: "keep",
    },
    skills: { cook: 78, mend: 44, forage: 46, heal: 36, teach: 52, farm: 30 },
  },
  {
    id: "jevlin",
    name: "Jevlin",
    age: 9,
    gender: "male",
    household: "vale",
    home: "vale",
    spouse: null,
    guardians: ["jevaary", "jevine"],
    dependents: [],
    mood: "restless, hoping to be useful",
    self: {
      temper: "restless and proud of almost helping",
      want: "to carry something heavy like Jevaary",
      fear: "being sent inside while work is happening",
      habit: "turns a chore into a game",
      pull: ["play", "forage"],
      custom: "learn",
    },
    skills: { play: 62, forage: 20, farm: 14 },
  },
  {
    id: "jevora",
    name: "Jevora",
    age: 6,
    gender: "female",
    household: "vale",
    home: "vale",
    spouse: null,
    guardians: ["jevaary", "jevine"],
    dependents: [],
    mood: "shy until someone looks at her",
    self: {
      temper: "shy, then suddenly bright",
      want: "to stay near Jevine",
      fear: "loud rain",
      habit: "repeats the last kind word she heard",
      pull: ["play"],
      custom: "learn",
    },
    skills: { play: 70, cook: 10, forage: 12 },
  },
  {
    id: "jevoric",
    name: "Jevoric",
    age: 67,
    gender: "male",
    household: "porch",
    home: "porch",
    spouse: null,
    guardians: [],
    dependents: ["jevina"],
    mood: "slow, a little amused",
    self: {
      temper: "slow, exact, and amused",
      want: "a young person to repeat the lesson back",
      fear: "the town forgetting a rule",
      habit: "answers a question with a question",
      pull: ["teach", "speak"],
      custom: "counsel",
    },
    skills: { teach: 88, farm: 36, heal: 32, cook: 24, haul: 6 },
  },
  {
    id: "jevina",
    name: "Jevina",
    age: 16,
    gender: "female",
    household: "porch",
    home: "porch",
    spouse: null,
    guardians: ["jevoric"],
    dependents: [],
    mood: "earnest, waiting to be trusted",
    self: {
      temper: "earnest and a little stubborn",
      want: "Jevoric to trust her with a real task",
      fear: "being treated as a small child",
      habit: "offers help before she is asked",
      pull: ["learn", "heal", "cook"],
      custom: "learn",
    },
    skills: { teach: 22, cook: 36, mend: 30, heal: 28, forage: 24, play: 34 },
  },
  {
    id: "jevon",
    name: "Jevon",
    age: 42,
    gender: "male",
    household: "market",
    home: "market",
    spouse: "jevara",
    guardians: [],
    dependents: ["jevik"],
    mood: "quick, watching who comes and goes",
    self: {
      temper: "quick and social",
      want: "the loft busy",
      fear: "an empty store",
      habit: "greets before he asks for anything",
      pull: ["haul", "mend", "speak"],
      custom: "provision",
    },
    skills: { haul: 58, mend: 34, farm: 24, cook: 22, teach: 16 },
  },
  {
    id: "jevara",
    name: "Jevara",
    age: 29,
    gender: "female",
    household: "market",
    home: "market",
    spouse: "jevon",
    guardians: [],
    dependents: ["jevik"],
    mood: "calm, one eye on Jevik",
    self: {
      temper: "precise and protective",
      want: "Jevik in sight and the cloth finished",
      fear: "losing the toddler in a crowd",
      habit: "speaks softly and says it once more",
      pull: ["mend", "care", "cook"],
      custom: "keep",
    },
    skills: { mend: 74, cook: 58, heal: 22, teach: 26 },
  },
  {
    id: "jevik",
    name: "Jevik",
    age: 3,
    gender: "male",
    household: "market",
    home: "market",
    spouse: null,
    guardians: ["jevon", "jevara"],
    dependents: [],
    mood: "sticky and sudden",
    self: {
      temper: "sudden, loud when left",
      want: "a lap or a game",
      fear: "no familiar adult nearby",
      habit: "points, then uses one word",
      pull: ["play"],
      custom: "learn",
    },
    skills: { play: 24 },
  },
  {
    id: "jevella",
    name: "Jevella",
    age: 23,
    gender: "female",
    household: "grove",
    home: "grove",
    spouse: null,
    guardians: [],
    dependents: [],
    mood: "alone on purpose, watching the path",
    self: {
      temper: "independent, dry, and observant",
      want: "the grove path walked before noon",
      fear: "the town crowding her hut",
      habit: "reports the weather before a feeling",
      pull: ["forage", "heal"],
      custom: "provision",
    },
    skills: { forage: 76, heal: 68, farm: 22, cook: 30, haul: 26, teach: 14 },
  },
  {
    id: "jevander",
    name: "Jevander",
    age: 47,
    gender: "male",
    household: "mill",
    home: "mill",
    spouse: "jevaine",
    guardians: [],
    dependents: ["jevita", "jevanne", "jevonel"],
    mood: "proud of the wheel, a little loud",
    self: {
      temper: "proud and practical",
      want: "the mill turning and the loft buying his flour",
      fear: "a broken wheel and an idle day",
      habit: "measures grain before he greets",
      pull: ["haul", "farm"],
      custom: "provision",
    },
    skills: { haul: 60, farm: 48, mend: 30, cook: 18 },
  },
  {
    id: "jevaine",
    name: "Jevaine",
    age: 44,
    gender: "female",
    household: "mill",
    home: "mill",
    spouse: "jevander",
    guardians: [],
    dependents: ["jevita", "jevanne", "jevonel"],
    mood: "busy, keeping three young ones in sight",
    self: {
      temper: "busy and exact",
      want: "cloth on the line and the children fed",
      fear: "Jevonel slipping toward the wheel",
      habit: "ties things down before she talks",
      pull: ["mend", "cook", "care"],
      custom: "keep",
    },
    skills: { mend: 64, cook: 50, teach: 20 },
  },
  {
    id: "jevita",
    name: "Jevita",
    age: 14,
    gender: "female",
    household: "mill",
    home: "mill",
    spouse: null,
    guardians: ["jevander", "jevaine"],
    dependents: [],
    mood: "restless to be more than a helper",
    self: {
      temper: "sharp and eager",
      want: "a lesson that is not a chore",
      fear: "being kept at the mill forever",
      habit: "asks why before she obeys",
      pull: ["learn", "mend"],
      custom: "learn",
    },
    skills: { mend: 28, teach: 18, play: 30, cook: 22 },
  },
  {
    id: "jevanne",
    name: "Jevanne",
    age: 8,
    gender: "female",
    household: "mill",
    home: "mill",
    spouse: null,
    guardians: ["jevander", "jevaine"],
    dependents: [],
    mood: "bright, following Jevita",
    self: {
      temper: "bright and sticky",
      want: "to do whatever Jevita is doing",
      fear: "the wheel and loud men",
      habit: "copies her sister",
      pull: ["play"],
      custom: "learn",
    },
    skills: { play: 55, cook: 8 },
  },
  {
    id: "jevonel",
    name: "Jevonel",
    age: 2,
    gender: "male",
    household: "mill",
    home: "mill",
    spouse: null,
    guardians: ["jevander", "jevaine"],
    dependents: [],
    mood: "small and sudden",
    self: {
      temper: "sudden",
      want: "Jevaine's hands",
      fear: "the open yard",
      habit: "holds cloth",
      pull: ["play"],
      custom: "learn",
    },
    skills: { play: 12 },
  },
  {
    id: "jevith",
    name: "Jevith",
    age: 74,
    gender: "female",
    household: "porch",
    home: "porch",
    spouse: null,
    guardians: [],
    dependents: [],
    mood: "dry, remembering how the town used to eat",
    self: {
      temper: "dry and ceremonial",
      want: "the old supper kept",
      fear: "the names being forgotten",
      habit: "corrects a custom in one sentence",
      pull: ["teach", "speak"],
      custom: "counsel",
    },
    skills: { teach: 80, cook: 40, heal: 24, haul: 4 },
  },
  {
    id: "jevory",
    name: "Jevory",
    age: 19,
    gender: "male",
    household: "market",
    home: "market",
    spouse: null,
    guardians: ["jevon"],
    dependents: [],
    mood: "hungry to out-trade Jevon",
    self: {
      temper: "ambitious and quick to take offense",
      want: "a share of the loft that is his",
      fear: "staying an apprentice",
      habit: "compares his pile to Jevon's",
      pull: ["haul", "mend", "speak"],
      custom: "provision",
    },
    skills: { haul: 36, mend: 24, teach: 10 },
  },
  {
    id: "jevoss",
    name: "Jevoss",
    age: 31,
    gender: "male",
    household: "rise",
    home: "rise",
    spouse: null,
    guardians: [],
    dependents: [],
    mood: "set on raising a roof of his own",
    self: {
      temper: "stubborn and physical",
      want: "walls that he laid",
      fear: "renting forever",
      habit: "stacks stone before he speaks",
      pull: ["haul", "farm"],
      custom: "provision",
    },
    skills: { haul: 70, farm: 24, mend: 40 },
  },
];

const AMBITIONS: Record<string, Ambition> = {
  jevaary: {
    independence: "wants the field to be his own name, not just the household's",
    love: "softest with Jevine, and frightened of failing the children",
    passion: "the crop itself, the count of it, the dirt under the nail",
    likes: "dawn, a full larder, quiet work",
    dislikes: "waste, a child out after dark, being hurried",
    career: "to be the grower the town trusts when the weather turns",
    plan: "add a second garden row and teach Jevlin one real job",
    project: "garden",
  },
  jevine: {
    independence: "keeps the hearth as her domain even when the field calls",
    love: "the children first, then Jevaary, said by name",
    passion: "feeding people and knowing who has gone quiet",
    likes: "a busy hearth, kind words, a named person",
    dislikes: "a silent toddler, a skipped meal, cold leftovers",
    career: "the keeper everyone comes to when they are hungry or lost",
    plan: "a standing supper that the whole town can count on",
    project: "garden",
  },
  jevlin: {
    independence: "wants a task that is his, not a game the adults invented",
    love: "admires Jevaary and shows it by trying to carry more",
    passion: "being useful outdoors",
    likes: "heavy things, races, being trusted",
    dislikes: "being sent inside, being called small",
    career: "to grow into the field beside his father",
    plan: "earn one row of the garden as his own",
    project: "garden",
  },
  jevora: {
    independence: "quiet until she chooses someone, then she stays",
    love: "sticks to Jevine and copies the last kind word",
    passion: "play that turns into a little song or a story",
    likes: "sitting close, flowers, being invited",
    dislikes: "loud rain, being left in a crowd",
    career: "too young for a trade, but she wants to be the one who remembers",
    plan: "learn every name in the town",
    project: "shrine",
  },
  jevoric: {
    independence: "answers to the lesson, not to being rushed",
    love: "patient with Jevina, proud when she repeats a rule back",
    passion: "teaching until the young can say it themselves",
    likes: "questions, exact words, a slow afternoon",
    dislikes: "forgotten rules, noise without a point",
    career: "the town's memory, while he still has the voice for it",
    plan: "leave Jevina able to teach without him",
    project: "shrine",
  },
  jevina: {
    independence: "will not be treated as a child if she can do the work",
    love: "wants Jevoric's trust more than praise",
    passion: "learning a real craft, hands first",
    likes: "being asked, a hard task, the porch in the morning",
    dislikes: "being dismissed, empty errands",
    career: "to stand as the next teacher, or a healer if the grove will have her",
    plan: "finish one lesson so well that Jevoric gives her the next",
    project: "shrine",
  },
  jevon: {
    independence: "the loft is his stage, and he likes being the one who greets",
    love: "fond of Jevara, watchful of Jevik, a little vain about both",
    passion: "exchange, news, who is carrying what",
    likes: "a busy door, a greeting, a good trade",
    dislikes: "an empty store, being ignored",
    career: "the trader the other households come to first",
    plan: "build the loft into a stall the whole square uses",
    project: "stall",
  },
  jevara: {
    independence: "her cloth and her eye on Jevik are not up for debate",
    love: "Jevik in sight, Jeven's greetings taken softly",
    passion: "mending until a thing is right, then saying it once more",
    likes: "finished cloth, a quiet child, precise hands",
    dislikes: "a crowd she cannot see through, rushed seams",
    career: "the mender people trust with their good things",
    plan: "a stall of her own cloth beside Jevon's trade",
    project: "stall",
  },
  jevik: {
    independence: "points at what he wants and expects the world to come closer",
    love: "a lap, a familiar voice, Jevara most of all",
    passion: "play, and being carried",
    likes: "games, food, being held",
    dislikes: "being alone, loud strangers",
    career: "none yet",
    plan: "stay near someone who knows his name",
    project: "garden",
  },
  jevander: {
    independence: "the mill is his, not the town's charity",
    love: "steady for Jevaine, proud of the children when they work",
    passion: "grain, the wheel, a fair measure",
    likes: "order, weight, a busy buyer",
    dislikes: "a stopped wheel, being undercut",
    career: "miller the loft cannot skip",
    plan: "a stall of flour that carries his name",
    project: "stall",
  },
  jevaine: {
    independence: "the cloth and the children are her say",
    love: "Jevonel first, then the girls, then Jevander",
    passion: "mending and keeping a house from fraying",
    likes: "finished seams, a quiet yard",
    dislikes: "the wheel unfenced, wasted cloth",
    career: "the mender the mill and the loft both call",
    plan: "cloth enough to trade, not only to patch",
    project: "stall",
  },
  jevita: {
    independence: "will not inherit the mill without a choice",
    love: "protective of Jevanne, wary of being owned by the work",
    passion: "learning a craft that is not grain",
    likes: "questions, the porch, being taken seriously",
    dislikes: "being told to watch the baby forever",
    career: "apprentice to the elders, then her own bench",
    plan: "one lesson from Jevith that her parents cannot dismiss",
    project: "shrine",
  },
  jevanne: {
    independence: "small, but she picks who she follows",
    love: "Jevita",
    passion: "play beside real work",
    likes: "her sister, flowers, stories",
    dislikes: "the wheel, being left",
    career: "not yet",
    plan: "stay near Jevita",
    project: "garden",
  },
  jevonel: {
    independence: "none yet",
    love: "Jevaine",
    passion: "being held",
    likes: "cloth, laps",
    dislikes: "open ground",
    career: "none",
    plan: "stay in sight",
    project: "garden",
  },
  jevith: {
    independence: "the customs are hers to keep, not to be voted",
    love: "the town as a whole, sharply, and Jevoric as a peer",
    passion: "ceremony, names, the hearth supper",
    likes: "correct speech, shared food, memory",
    dislikes: "new ways that skip the old meal",
    career: "culture keeper beside Jevoric",
    plan: "see one more generation keep the supper",
    project: "shrine",
  },
  jevory: {
    independence: "wants a name that is not 'Jevon's boy'",
    love: "thin so far, mostly ambition",
    passion: "trade, and beating Jevon at it",
    likes: "a crowd, a bargain, being seen",
    dislikes: "being corrected, an empty purse",
    career: "trader in his own right",
    plan: "a corner of the loft, then a stall",
    project: "stall",
  },
  jevoss: {
    independence: "will not live in another man's house",
    love: "unattached, jealous of families only in passing",
    passion: "stone, walls, a roof he owns",
    likes: "weight, a straight course, quiet credit",
    dislikes: "rent, being told the rise is not his",
    career: "builder",
    plan: "a house, brick by brick, on the rise",
    project: "house",
  },
  jevella: {
    independence: "the grove is hers and she will not have it crowded",
    love: "wary, but she softens for Jevine and for anyone actually hurt",
    passion: "the path, the herbs, weather read before feelings",
    likes: "early walks, quiet, a true report",
    dislikes: "the town pressing in, small talk with no news",
    career: "the forager and healer people send for, not a neighbor they manage",
    plan: "an orchard edge that is still hers",
    project: "orchard",
  },
};

function personFrom(seed: Seed): Person {
  return {
    id: seed.id,
    name: seed.name,
    age: seed.age,
    gender: seed.gender,
    band: bandFor(seed.age),
    household: seed.household,
    home: seed.home,
    spouse: seed.spouse,
    guardians: seed.guardians,
    dependents: seed.dependents,
    self: { ...seed.self, ambition: AMBITIONS[seed.id] ?? AMBITIONS.jevaary },
    skills: skills(seed.skills),
    place: seed.home,
    x: 0,
    y: 0,
    facing: "front",
    hunger: 28,
    energy: 82,
    belonging: 58,
    distress: false,
    choresToday: 0,
    projectProgress: 0,
    authority: seed.age >= 60 ? 76 : seed.age >= 18 ? 42 : seed.age >= 13 ? 16 : 4,
    bricks: 0,
    alive: true,
    intent: null,
    speech: null,
    memory: [],
    mood: seed.mood,
    innerNote: seed.self.habit,
    because: "waking up at home",
  };
}

function bond(a: string, b: string, score: number, note: string, love = 25): Bond {
  return { a, b, score, note, love, jealousy: 0, hate: 0, rivalry: 8 };
}

export function createCast(): {
  people: Person[];
  bonds: Bond[];
  food: Record<string, number>;
  wood: Record<string, number>;
  stone: Record<string, number>;
  cloth: Record<string, number>;
} {
  return {
    people: SEEDS.map(personFrom),
    food: { vale: 8, market: 6, porch: 5, grove: 4, mill: 6, rise: 3 },
    bonds: [
      bond("jevaary", "jevine", 86, "spouses who split the day between field and hearth"),
      bond("jevaary", "jevlin", 84, "father and son"),
      bond("jevaary", "jevora", 84, "father and daughter"),
      bond("jevine", "jevlin", 86, "mother and son"),
      bond("jevine", "jevora", 90, "mother and daughter, rarely apart"),
      bond("jevlin", "jevora", 74, "siblings"),
      bond("jevon", "jevara", 82, "spouses at the loft"),
      bond("jevon", "jevik", 80, "father of a toddler"),
      bond("jevara", "jevik", 92, "mother, keeps him in sight"),
      bond("jevoric", "jevina", 78, "elder and granddaughter, teacher and apprentice"),
      bond("jevine", "jevella", 48, "neighbors who trade food and herbs"),
      bond("jevaary", "jevoric", 55, "respect, and a little impatience"),
      bond("jevon", "jevella", 40, "he buys what she forages"),
      bond("jevander", "jevaine", 84, "spouses at the mill", 78),
      bond("jevander", "jevita", 70, "father and daughter"),
      bond("jevaine", "jevita", 80, "mother and daughter"),
      bond("jevaine", "jevanne", 84, "mother and daughter"),
      bond("jevaine", "jevonel", 90, "mother and toddler", 88),
      bond("jevander", "jevonel", 76, "father and toddler"),
      bond("jevita", "jevanne", 86, "sisters", 70),
      bond("jevoric", "jevith", 74, "elders who keep the customs", 40),
      bond("jevith", "jevina", 60, "the elder is strict and fond"),
      bond("jevon", "jevory", 48, "master and apprentice, already rival", 10),
      bond("jevaary", "jevoss", 36, "both want land and neither yields", 8),
      bond("jevaine", "jevine", 66, "sisters"),
    ],
    wood: { vale: 4, market: 3, porch: 2, grove: 5, mill: 4, rise: 2 },
    stone: { vale: 1, market: 1, porch: 1, grove: 1, mill: 2, rise: 4 },
    cloth: { vale: 2, market: 3, porch: 1, grove: 1, mill: 4, rise: 1 },
  };
}
